config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'public/sessions#guest_sign_in'
  end
  scope module: :public do
    root 'homes#top'
    resources :songs, only: [:new, :create, :index, :show] do
      collection do
        get 'search_with_songs' => "songs#search"
        get 'search_with_posts' => "posts#search"
        get 'genre'
      end
      resources :posts, only: [:create, :show, :edit, :update, :destroy] do
        resources :comments, only: [:create, :destroy]
        resource :like, only: [:create, :destroy]
      end
    end
    get 'users/mypage' => 'users#show'
    get 'users/:id/likes' => 'users#like', as: 'like'
    get 'users/information/edit' => 'users#edit'
    patch 'users/information' => 'users#update'
    get 'users/confirm_withdraw' => 'users#confirm_withdraw', as: 'confirm_withdraw'
    patch 'users/withdraw' => 'users#withdraw', as: 'withdraw'
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root 'homes#top'
    resources :songs, only:[:index, :show] do
      collection do
        get 'search'
        get 'genre'
      end
    end
    resources :users, only:[:index, :show, :edit, :update]
    resources :posts, only:[:show, :destroy] do
      collection do
        get 'search'
      end
      resources :comments, only: [:create, :destroy]
      resource :like, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :song
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end

  def self.likes(user, page, per_page)
    includes(:likes)
      .where(likes: {user_id: user.id})
      .order(created_at: :desc)
      .page(page)
      .per(per_page)
  end
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
  validates :song_name, presence: true
  validates :artist_name, presence: true
  validate :unique_combination

  def unique_combination
    if Song.exists?(song_name: song_name)
      if Song.exists?(song_name: song_name, artist_name: artist_name)
        errors.add(:base, '同じ曲名とアーティスト名の組み合わせは既に存在します。曲検索で確認してください。')
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :songs, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/likes_controller.rb
class Admin::LikesController < ApplicationController
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_song_path(post.song.id)
  end

  def search
    if params[:keyword].present?
      @posts = Post.where('listen LIKE ? or text LIKE ?', "%#{params[:keyword]}%", "%#{params[:keyword]}%")
      @keyword = params[:keyword]
    else
      @posts = Post.all
    end
  end

  private

  def post_params
    params.require(:post).permit(:song_id, :listen, :text)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  
end

app/controllers/admin/songs_controller.rb
class Admin::SongsController < ApplicationController
  def index
    @songs = Song.page(params[:page])
  end

  def show
    @song = Song.find(params[:id])
    @posts = Post.where(song_id: @song.id).page(params[:page])
  end

  def search
    if params[:keyword].present?
      @songs = Song.where('song_name LIKE ? or artist_name LIKE ? or genre LIKE ?', "%#{params[:keyword]}%", "%#{params[:keyword]}%", "%#{params[:keyword]}%")
      @keyword = params[:keyword]
    else
      @songs = Song.all
    end
  end

  def genre
    if params[:genre].present?
      genres = params[:genre].split(",") # パラメータのジャンルを配列に分割する
      @songs = Song.where(genre: genres) # ジャンルが配列に含まれる曲を取得する
      @genre = params[:genre]
    else
      @songs = Song.all
      @genre = nil # ジャンルが指定されていない場合は、@genre変数にはnilを設定しておく
    end
  end

  private

  def song_params
    params.require(:song).permit(:user_id, :song_name, :artist_name, :genre, posts_attributes:[:id, :song_id, :listen, :text])
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :is_deleted)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      admin_songs_path
    else
      songs_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
      admin_session_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/likes_helper.rb
module Admin::LikesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/songs_helper.rb
module Admin::SongsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/posts/search.html.erb
<h2>検索結果 "<%= @keyword %>"</h2>
<div class="container m-5">
  <h3>レビュー一覧</h3>
  <div class= "center-block">
    <div class="col-xs-1">
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>ユーザー名</th>
            <th>どんな時に聴きたいか</th>
            <th>レビュー</th>
          </tr>
        </thead>
        <% @posts.each do |post| %>
          <tbody>
            <tr>
              <td><%= link_to post.user.name, admin_post_path(post.id) %></td>
              <td><%= post.listen %></td>
              <td><%= post.text %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="m-3">
    <h3>レビュー詳細</h3>
    <div>
      <p>ユーザー名/<%= @post.user.name %></p>
      <p>どんな時に聴きたいか <%= @post.listen %></p>
      <p>レビュー <%= @post.text %></p>
      <%= @post.created_at.strftime('%Y年%m月%d日') %>
      <%= link_to '削除', admin_post_path(@post.id), method: :delete %>
    </div>

    <%= link_to '曲詳細に戻る', admin_song_path(@post.song.id) %>
  </div>
</div>

app/views/admin/songs/genre.html.erb
<h2>検索結果 "<%= @genre %>"</h2>
<div class="container m-5">
  <h3>曲一覧</h3>
  <div class= "center-block">
    <div class="col-xs-1">
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>曲ID</th>
            <th>曲名</th>
            <th>アーティスト名</th>
          </tr>
        </thead>
        <% @songs.each do |song| %>
          <tbody>
            <tr>
              <td><%= song.id %></td>
              <td><%= link_to song.song_name, admin_song_path(song.id) %></td>
              <td><%= song.artist_name %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/songs/index.html.erb
<div class="container">
  <div class="row m-3">
    <div class="col-lg-4">
      <div>
        <span>曲検索（曲名、アーティスト名、ジャンル名）</span>
        <%= form_with url: search_admin_songs_path, local: true, method: :get do |f| %>
          <%= f.text_field :keyword %>
          <%= f.submit "検索" %>
        <% end %>
      </div>

      <div>
        <span>レビュー検索（どんな時に聴きたいか、キーワード）</span>
        <%= form_with url: search_admin_posts_path, local: true, method: :get do |f| %>
          <%= f.text_field :keyword %>
          <%= f.submit "検索" %>
        <% end %>
      </div>

      <div class="accbox">
        <span>ジャンルで絞り込む</span>
        <%= form_with url: genre_admin_songs_path, local: true, method: :get do |f| %>
          <div class="accshow">
            ジャンルを選択<br>
            <input type="checkbox" name="genre[]" value="J-POP">J-POP<br>
            <input type="checkbox" name="genre[]" value="ロック">ロック<br>
            <input type="checkbox" name="genre[]" value="K-POP">K-POP<br>
            <input type="checkbox" name="genre[]" value="演歌">演歌<br>
            <input type="checkbox" name="genre[]" value="クラシック">クラシック<br>
            <input type="checkbox" name="genre[]" value="洋楽">洋楽<br>
            <input type="checkbox" name="genre[]" value="アニメ">アニメ<br>
            <input type="submit" value="絞り込む">
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-lg-8">
      <h3>曲一覧</h3>
      <div class= "center-block">
        <div class="col-xs-1">
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th>曲ID</th>
                <th>曲名</th>
                <th>アーティスト名</th>
              </tr>
            </thead>
            <% @songs.each do |song| %>
              <tbody>
                <tr>
                  <td><%= song.id %></td>
                  <td><%= link_to song.song_name, admin_song_path(song.id) %></td>
                  <td><%= song.artist_name %></td>
                </tr>
              </tbody>
            <% end %>
          </table>
          <%= paginate @songs %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/songs/search.html.erb
<h2>検索結果 "<%= @keyword %>"</h2>
<div class="container m-5">
  <h3>曲一覧</h3>
  <div class= "center-block">
    <div class="col-xs-1">
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>曲ID</th>
            <th>曲名</th>
            <th>アーティスト名</th>
          </tr>
        </thead>
        <% @songs.each do |song| %>
          <tbody>
            <tr>
              <td><%= song.id %></td>
              <td><%= link_to song.song_name, admin_song_path(song.id) %></td>
              <td><%= song.artist_name %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/songs/show.html.erb
<div class="container">
  <div class="row m-3">
    <div class="col-lg-4">
      <div>
        <h3><%= @song.song_name %>の詳細</h3>
        <p>曲名 <%= @song.song_name %></p>
        <p>アーティスト名 <%= @song.artist_name %></p>
        <p>ジャンル <%= @song.genre %></p>
      </div>
    </div>

    <div class="col-lg-8">
      <h3>レビュー一覧</h3>
      <div class= "center-block">
        <div class="col-xs-1">
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th>ユーザー名</th>
                <th>どんな時に聴きたいか</th>
                <th>レビュー</th>
              </tr>
            </thead>
            <% @posts.each do |post| %>
              <tbody>
                <tr>
                  <td><%= link_to post.user.name, admin_post_path(post.id) %></td>
                  <td><%= post.listen %></td>
                  <td><%= post.text %></td>
                </tr>
              </tbody>
            <% end %>
          </table>
          <%= paginate @posts %>
        </div>
      </div>
   </div>
  </div>
</div>

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="m-3">
    <h3><%= @user.name %>さんの会員情報編集</h3>
    <div clss="row">
      <div class="col-xs-12">
        <%= form_with model: @user, url: admin_user_path(@user.id) do |f| %>

          <div>
            <p>会員ID <%= @user.id %></p>
            <p>ユーザー名 <%= f.text_field :name %></p>
            <p>メールアドレス <%= f.text_field :email %></p>
            <p>
              会員ステータス
              <%= f.radio_button :is_deleted, "false" %>
              <%= f.label :is_deleted, "有効" %>
              <%= f.radio_button :is_deleted, "true" %>
              <%= f.label :is_deleted, "退会" %>
            </p>
          </div>
          <%= f.submit "保存", class: "btn btn-success" %>

        <% end %>

        <div class="m-3">
          <%= link_to "ユーザー詳細に戻る", admin_user_path(@user.id) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="m-3">
    <h3>ユーザー一覧</h3>
    <div class="center-block">
      <div class="col-xs-1">
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>ユーザーID</th>
              <th>ユーザー名</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <% @users.each do |user| %>
            <tbody>
              <tr>
                <td><%= user.id %></td>
                <td>
                  <%= link_to admin_user_path(user.id) do %>
                    <%= user.name %>
                  <% end %>
                </td>
                <td>
                  <% if user.is_deleted == false %>
                    有効
                  <% else %>
                    退会
                  <% end %>
                </td>
              </tr>
            </tbody>
          <% end %>
        </table>
        <%= paginate @users %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="m-3">
    <h3><%= @user.name %>さんの会員詳細</h3>
    <div class="center-block">
      <div>
        <div class="col-xs-7">
          <p>会員ID <%= @user.id %></p>
          <p>ユーザー名 <%= @user.name %></p>
          <p>メールアドレス <%= @user.email %></p>
          <p>
            会員ステータス
            <% if @user.is_deleted == false %>
              有効
            <% else %>
              退会
            <% end %>
          </p>
        </div>
      </div>
    </div>
    <span><%= link_to "編集", edit_admin_user_path(@user.id), class: "btn btn-success" %></span>
  </div>
</div>