config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'public/sessions#guest_sign_in'
  end
  scope module: :public do
    root 'homes#top'
    resources :songs, only: [:new, :create, :index, :show] do
      collection do
        get 'search_with_songs' => "songs#search"
        get 'search_with_posts' => "posts#search"
        get 'genre'
      end
      resources :posts, only: [:create, :show, :edit, :update, :destroy] do
        resources :comments, only: [:create, :destroy]
        resource :like, only: [:create, :destroy]
      end
    end
    get 'users/mypage' => 'users#show'
    get 'users/:id/likes' => 'users#like', as: 'like'
    get 'users/information/edit' => 'users#edit'
    patch 'users/information' => 'users#update'
    get 'users/confirm_withdraw' => 'users#confirm_withdraw', as: 'confirm_withdraw'
    patch 'users/withdraw' => 'users#withdraw', as: 'withdraw'
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root 'homes#top'
    resources :songs, only:[:index, :show] do
      collection do
        get 'search'
        get 'genre'
      end
    end
    resources :users, only:[:index, :show, :edit, :update]
    resources :posts, only:[:show, :destroy] do
      collection do
        get 'search'
      end
      resources :comments, only: [:create, :destroy]
      resource :like, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :song
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end

  def self.likes(user, page, per_page)
    includes(:likes)
      .where(likes: {user_id: user.id})
      .order(created_at: :desc)
      .page(page)
      .per(per_page)
  end
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
  validates :song_name, presence: true
  validates :artist_name, presence: true
  validate :unique_combination

  def unique_combination
    if Song.exists?(song_name: song_name)
      if Song.exists?(song_name: song_name, artist_name: artist_name)
        errors.add(:base, '同じ曲名とアーティスト名の組み合わせは既に存在します。曲検索で確認してください。')
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :songs, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/likes_controller.rb
class Admin::LikesController < ApplicationController
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_song_path(post.song.id)
  end

  def search
    if params[:keyword].present?
      @posts = Post.where('listen LIKE ? or text LIKE ?', "%#{params[:keyword]}%", "%#{params[:keyword]}%")
      @keyword = params[:keyword]
    else
      @posts = Post.all
    end
  end

  private

  def post_params
    params.require(:post).permit(:song_id, :listen, :text)
  end
end

app/controllers/admin/songs_controller.rb
class Admin::SongsController < ApplicationController
  def index
    @songs = Song.page(params[:page])
  end

  def show
    @song = Song.find(params[:id])
    @posts = Post.where(song_id: @song.id).page(params[:page])
  end

  def search
    if params[:keyword].present?
      @songs = Song.where('song_name LIKE ? or artist_name LIKE ? or genre LIKE ?', "%#{params[:keyword]}%", "%#{params[:keyword]}%", "%#{params[:keyword]}%")
      @keyword = params[:keyword]
    else
      @songs = Song.all
    end
  end

  def genre
    if params[:genre].present?
      genres = params[:genre].split(",") # パラメータのジャンルを配列に分割する
      @songs = Song.where(genre: genres) # ジャンルが配列に含まれる曲を取得する
      @genre = params[:genre]
    else
      @songs = Song.all
      @genre = nil # ジャンルが指定されていない場合は、@genre変数にはnilを設定しておく
    end
  end

  private

  def song_params
    params.require(:song).permit(:user_id, :song_name, :artist_name, :genre, posts_attributes:[:id, :song_id, :listen, :text])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :is_deleted)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      admin_songs_path
    else
      songs_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
      admin_session_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/likes_helper.rb
module Admin::LikesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/songs_helper.rb
module Admin::SongsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/c9084df719.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse shadow-sm">
      <div class="container">
        <nav class="nav navbar-left">
          <span class="nav-link text-dark"><i class="fa-solid fa-headphones"></i>Musearch</span>
        </nav>
        <nav class="nav navbar-right">
          <ul class="navbar ml-auto list-unstyled">
            <% if user_signed_in? %>
              <li>
                <%= link_to new_song_path do %>
                  <span class="nav-link text-dark"><i class="fa-solid fa-pen-to-square"></i>新規投稿</span>
                <% end %>
              </li>
              <li>
                <%= link_to songs_path do %>
                  <span class="nav-link text-dark"><i class="fa-solid fa-music"></i>曲一覧</span>
                <% end %>
              </li>
              <li>
                <%= link_to users_mypage_path do %>
                  <span class="nav-link text-dark"><i class="fa-solid fa-circle-user"></i>プロフィール</span>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <span class="nav-link text-dark"><i class="fa-solid fa-sign-out-alt"></i>ログアウト</span>
                <% end %>
              </li>
            <% elsif admin_signed_in? %>
              <li>
                <%= link_to admin_songs_path do %>
                  <span class="nav-link text-dark"><i class="fa-solid fa-music"></i>曲一覧</span>
                <% end %>
              </li>
              <li>
                <%= link_to admin_users_path do %>
                  <span class="nav-link text-dark"><i class="fa-solid fa-users"></i>ユーザー一覧</span>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_admin_session_path, method: :delete do %>
                  <span class="nav-link text-dark"><i class="fa-solid fa-sign-out-alt"></i>ログアウト</span>
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to new_user_registration_path do %>
                  <span class="nav-link text-dark"><i class="fa-solid fa-user-plus"></i>新規登録</span>
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path do %>
                  <span class="nav-link text-dark"><i class="fa-solid fa-sign-in-alt"></i>ログイン</span>
                <% end %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <main class="mb-auto">
      <%= yield %>
    </main>

    <footer class="bg-dark pt-5 pb-4">
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p></p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>